services:
  # SERVICIO 1: Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: pgli_db
    restart: always
    environment:
      - POSTGRES_USER=pgli_admin
      - POSTGRES_PASSWORD=pgli_password
      - POSTGRES_DB=pgli_local
    ports:
      - "5433:5432" # Puerto 5433 para acceso externo (DBeaver/pgAdmin)
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pgli_network

  # SERVICIO 2: Backend Spring Boot
  api:
    build: .
    container_name: pgli_api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      # Inyección de variables para resolver ${SPRING_DATASOURCE_URL} y demás
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pgli_local
      - SPRING_DATASOURCE_USERNAME=pgli_admin
      - SPRING_DATASOURCE_PASSWORD=pgli_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - pgli_network

# Definición de volúmenes persistentes
volumes:
  pg_data:

# Definición de la red virtual interna
networks:
  pgli_network:
    driver: bridge